model:
  cldm:
    target: terediff.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      use_chinese_clip: true
      unet_cfg:
        use_checkpoint: True
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        model_name: "ViT-B-16"
        pretrained: "zh"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  swinir:
    target: terediff.model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  diffusion:
    target: terediff.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: True
      parameterization: v

dataset:
  dataset_type: realsr
  train:
    target: terediff.dataset.realesrgan.RealESRGANDataset
    params:
      file_list: /path/to/chinese/dataset
      file_backend_cfg:
        target: terediff.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: none
      use_hflip: false
      use_rot: false
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob: 0.1
      blur_sigma: [0.2, 3]
      betag_range: [0.5, 4]
      betap_range: [1, 2]
      blur_kernel_size2: 21
      kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob2: 0.1
      blur_sigma2: [0.2, 1.5]
      betag_range2: [0.5, 4]
      betap_range2: [1, 2]
      final_sinc_prob: 0.8
      p_empty_prompt: 0.2
      data_args: {
        'mode': 'TRAIN',
        'datasets': ['chinese_text_dataset'], 
        'ann_path': '/path/to/chinese/annotations.json',
        'model_img_size': [512, 512],
      }

  val:
    target: terediff.dataset.realesrgan.RealESRGANDataset
    params:
      file_list: /path/to/chinese/dataset
      file_backend_cfg:
        target: terediff.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: none
      use_hflip: false
      use_rot: false
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      sinc_prob: 0.1
      blur_sigma: [0.2, 3]
      betag_range: [0.5, 4]
      betap_range: [1, 2]
      blur_kernel_size2: 21
      kernel_list2: ['iso', 'aniso']
      kernel_prob2: [0.5, 0.5]
      sinc_prob2: 0.1
      blur_sigma2: [0.2, 1.5]
      betag_range2: [0.5, 4]
      betap_range2: [1, 2]
      final_sinc_prob: 0.8
      p_empty_prompt: 0.5
      data_args: {
        'mode': 'VAL',
        'datasets': ['chinese_text_dataset'], 
        'ann_path': '/path/to/chinese/annotations.json',
        'model_img_size': [512, 512],
      }

train_batch_transform:
  target: terediff.dataset.batch_transform.RealESRGANBatchTransform
  params:
    use_sharpener: false
    queue_size: 160
    resize_prob: [0.3, 0.4, 0.3]
    resize_range: [0.15, 1.5]
    gray_noise_prob: 0.4
    gaussian_noise_prob: 0.5
    noise_range: [1, 30]
    poisson_scale_range: [0.05, 3]
    jpeg_range: [30, 95]
    second_blur_prob: 0.8
    stage2_scale: [0.6, 1.2]
    resize_prob2: [0.3, 0.4, 0.3]
    resize_range2: [0.3, 1.2]
    gray_noise_prob2: 0.4
    gaussian_noise_prob2: 0.5
    noise_range2: [1, 25]
    poisson_scale_range2: [0.05, 2.5]
    jpeg_range2: [30, 95]

val_batch_transform:
  target: terediff.dataset.batch_transform.RealESRGANBatchTransform
  params:
    use_sharpener: false
    queue_size: 160
    resize_prob: [0.2, 0.7, 0.1]
    resize_range: [0.15, 1.5]
    gray_noise_prob: 0.4
    gaussian_noise_prob: 0.5
    noise_range: [1, 30]
    poisson_scale_range: [0.05, 3]
    jpeg_range: [30, 95]
    second_blur_prob: 0.8
    stage2_scale: 0.8
    resize_prob2: [0.3, 0.4, 0.3]
    resize_range2: [0.3, 1.2]
    gray_noise_prob2: 0.4
    gaussian_noise_prob2: 0.5
    noise_range2: [1, 25]
    poisson_scale_range2: [0.05, 2.5]
    jpeg_range2: [30, 95]

train:
  sd_path: ./weights/sd2.1-base-zsnr-laionaes5.ckpt
  swinir_path: ./weights/realesrgan_s4_swinir_100k.pth
  learning_rate: 1e-5
  total_steps: 200000
  log_every_t: 1000
  val_check_interval: 10000
  num_sanity_val_steps: 2
  accumulate_grad_batches: 1

log_args:
  log_tool: wandb
  wandb_key: YOUR_WANDB_KEY
  wandb_proj_name: terediff_chinese

exp_args:
  mode: TRAIN
  model_name: terediff_stage1_chinese
  finetuning_method: image_restoration_module
  testr_ckpt_dir: 
  resume_ckpt_dir: 
  save_ckpt_dir: ./ckpts/stage1_chinese
  save_val_img_dir: ./val_imgs/stage1_chinese